"""

Revision ID: 6972630ad07c
Revises: 9e43a4f6a442
Create Date: 2021-11-02 10:29:25.364155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6972630ad07c'
down_revision = '9e43a4f6a442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
